spring.application.name=healthypaws
spring.datasource.url=jdbc:mysql://localhost:3307/healthypaws_db
spring.datasource.username=root
spring.datasource.password=redhat
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=merukarpriti@gmail.com
# PASTE THE 16-DIGIT CODE HERE
spring.mail.password=tyac nytq npmz khme
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Enable file uploads
spring.servlet.multipart.enabled=true

# Set max file size (e.g., 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

